### PR TITLE
Created HOL

### PR DESCRIPTION
**Pull request by jtuliani**
Created HOL. Azure Migrate assessment phase not done yet (blocked)

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan,
To send this for SME review, I need one pull request with the entire workshop.  Please combine the pull requests ASAP.

**Comment by jtuliani** [comment]
@DawnmarieDesJardins Would it be OK if we just merge the PRs into master? There's no existing content to overwrite, so I don't see how it would cause a problem. Easier than merging the separate PRs into one PR.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan,
Quick question for you.  You PR comment says "Azure Migrate assessment phase not done yet (blocked)." Does that mean there is part of the lab not working yet?  We ask SMEs to work through all the way through the lab during review so I want to make sure that's possible.  Thanks

**Comment by DawnmarieDesJardins** [comment]
Since this is brand new, merging into master should be just fine!  I can point the SMEs to the main page for the review.  You'll need to build out the ReadMe page according to the templates as well please.  Abstract, products & services, etc.

**Comment by jtuliani** [comment]
@DawnmarieDesJardins Yes, that's what it means. However, I've met with the Azure Migrate team this week, and we have found a way forward. (There was an issue with DNS which we can work around by editing the hosts file on the Azure Migrate appliance VM.) I will write up that last part of the lab just as soon as I get time. The remainder of the lab is testable without that step--there's no dependencies--but of course it would be better if possible to wait until that last piece is filled in.

**Comment by DawnmarieDesJardins** [comment]
Can you give me an ETA?  We're presenting this workshop at the next Boot Camp and we're incredibly tight on time.  I have several steps I need to take after reviews to publish and the workshop planners need me to hand off to them at the end of April.

**Comment by DawnmarieDesJardins** [comment]
Can you give me an ETA?  We're presenting this workshop at the next Boot Camp and we're incredibly tight on time.  I have several steps I need to take after reviews to publish and the workshop planners need me to hand off to them at the end of April.

**Comment by jtuliani** [comment]
Hi @DawnmarieDesJardins ...I should be all done by EOD Tuesday or worst case Wednesday next week.

**Comment by jtuliani** [comment]
@DawnmarieDesJardins All done. Both the WDS and HOL are checked in to Master and ready for review.

**Pull request merged**
